# Site settings
title: Skidmore
slogan: Personal Website
email:
author: Zachary Skidmore
description:
url:

# Build settings
permalink: :title/
sass:
  sass_dir: _sass
include: ['_sass']
markdown: kramdown
kramdown:
  auto_ids: true

# favicons
favicon-32x32: favicon_32x32.png
